security:
    type:     annotation
    resource: Podcast\UserBundle\Controller\SecurityController
    
users:
    type:     rest
    prefix:   /user
    resource: Podcast\UserBundle\Controller\UserController
