parameters:
    vendor_security.authentication_handler: Podcast\UserBundle\Handler\AuthenticationHandler
    podcast.listener.before_controller: Podcast\UserBundle\Listener\BeforeControllerListener

services:
    authentication_handler:
        class:  %vendor_security.authentication_handler%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    before_controller:
        class: %podcast.listener.before_controller%
        scope: request
        tags:
            - { name:'kernel.event_listener', event: 'kernel.controller', method: 'onKernelController' }
        arguments:    [@security.context]