imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:       { fallback: 'en' }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - "MopaBootstrapBundle:Form:fields.html.twig"
#            - "BraincraftedBootstrapBundle:Form:form_div_layout.html.twig"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'          

mopa_bootstrap:
    form:
        templating: true
        render_fieldset: false
        show_legend: false
        show_child_legend: false
        render_required_asterisk: true
        checkbox_label: 'both'
        error_type: 'block'
        collection:
            widget_remove_btn:
                attr:
                    class: btn
                icon: null
                icon_color: null
            widget_add_btn:
                attr:
                    class: btn
                icon: null
                icon_color: null



knp_menu:
#   twig:
#       template: "BraincraftedBootstrapBundle:Menu:menu.html.twig"  
   # if true, enables the helper for PHP templates
   templating: false 
   # The renderer to use, list is also available by default
   default_renderer: twig
   
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: false                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        #pagination: KnpPaginatorBundle:Pagination:sliding.html.twig   
        pagination: BraincraftedBootstrapBundle:Pagination:pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [PodcastMainBundle, FOSUserBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: “\.less$”
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# FOS User Bundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Podcast\UserBundle\Entity\User
    registration:
        form:
            type: podcast_mainbundle_registrationformtype
    
fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            rss: false
            xml: false
            json: true
        templating_formats:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        view_response_listener: 'force'
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
            rss: 'application/rss+xml'
            jpg: 'image/jpeg'
            png: 'image/png'
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        default_priorities: ['json', html, '*/*']
        fallback_format: json
        prefer_extension: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': 403
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

        
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }        
        
fkr_simple_pie:
    cache_enabled: false
    cache_dir: %kernel.cache_dir%/rss
    cache_duration: 3600

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB
