parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: D33pth0ught

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            RyoHazuki
    
    node_base_path:    /usr/lib/nodejs
    node_lib_path:     /usr/lib/nodejs/npm/lib
    node_modules_path: /usr/lib/nodejs/npm/node_modules
    
    behat_paths_base: /