<?php

namespace Podcast\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Podcast\UserBundle\Entity\User;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

}
