podcasts:
    type:     rest
    resource: Podcast\MainBundle\Controller\PodcastsController

categories:
    resource: Podcast\MainBundle\Controller\CategoryController

episodes:
    type:     rest
    resource: Podcast\MainBundle\Controller\EpisodesController
