##PodcastMainBundle_homepage:
##    pattern:  /
##    defaults: { _controller: PodcastMainBundle:Default:index, _format: json }
##    options:
##      expose: true
##    requirements:
##      _method: GET
##
#
#podcasts:
#    type:     rest
#    resource: Podcast\MainBundle\Controller\PodcastsController
#
#users:
#    type:     rest
#    resource: Podcast\MainBundle\Controller\UsersController
#    
#episodes:
#    type:     rest
#    resource: Podcast\MainBundle\Controller\EpisodesController
#    
##      
##PodcastMainBundle_create:
##    pattern:  /
##    defaults: { _controller: PodcastMainBundle:Default:create, _format: json }
##    options:
##      expose: true
##    requirements:
##      _method: POST
##      
##PodcastMainBundle_delete:
##    pattern:  /
##    defaults: { _controller: PodcastMainBundle:Default:delete, _format: json }
##    options:
##      expose: true
##    requirements:
##      _method: DELETE   
##      
##PodcastMainBundle_show:
##  pattern: /{id}
##  defaults: { _controller: PodcastMainBundle:Default:show }
##  options:
##    expose: true
##      
#PodcastMainBundle_new:
#  pattern: /new
#  defaults: { _controller: PodcastMainBundle:Default:new }
##  
##PodcastMainBundle_user_playlists:
##  pattern: /user/get-playlists
##  defaults: {_controller: "PodcastMainBundle:Default:playlists"}
##  options:
##    expose: true  
##    
##PodcastMainBundle_user_subscriptions:
##  pattern: /user/get-subscriptions
##  defaults: {_controller: "PodcastMainBundle:Default:subscriptions"}
##  options:
##    expose: true
##  
##PodcastMainBundle_user_listened_to:
##  pattern: /user/listened-to/{id}
##  defaults: {_controller: "PodcastMainBundle:Default:listenedTo"}
##  options:
##    expose: true
##  
##PodcastMainBundle_add_subscription:
##  pattern: /user/add-subscription
##  defaults: {_controller: "PodcastMainBundle:Default:addSubscription", _format:"json"}
##  options:
##    expose: true
##    
##PodcastMainBundle_add_episode_to_playlist:
##  pattern: /user/add-episode-to-playlist
##  defaults: {_controller: "PodcastMainBundle:Playlist:addPodcast" }
##  options:
##    expose: true
##    
##playlist_remove_episode:
##  pattern: /playlist/remove-episode/{episode_id}/{playlist_id}
##  defaults: {_controller: "PodcastMainBundle:Playlist:removeEpisode" }
##  requirements: { _method: post }
##  options:
##    expose: true
##    
##PodcastMainBundle_get_most_subscribed:
##  pattern: /podcasts/most-subscribed/all
##  defaults: {_controller: "PodcastMainBundle:Default:mostSubscribed" }
##  options:
##    expose: true
##    
##playlist:
##  pattern:  /playlist/
##  defaults: { _controller: "PodcastMainBundle:Playlist:index" }
##  options:
##    expose: true
##    
##playlist_show:
##    pattern:  /playlist/{id}/show
##    defaults: { _controller: "PodcastMainBundle:Playlist:show" }
##
##playlist_new:
##    pattern:  /playlist/new
##    defaults: { _controller: "PodcastMainBundle:Playlist:new" }
##
##playlist_create:
##    pattern:  /playlist/create
##    defaults: { _controller: "PodcastMainBundle:Playlist:create" }
##    requirements: { _method: post }
##
##playlist_blind_create:
##  pattern:  /playlist/blind-create
##  defaults: { _controller: "PodcastMainBundle:Playlist:blindCreate" }
##  options:
##    expose: true
##    
##playlist_edit:
##    pattern:  /playlist/{id}/edit
##    defaults: { _controller: "PodcastMainBundle:Playlist:edit" }
##
##playlist_update:
##    pattern:  /playlist/{id}/update
##    defaults: { _controller: "PodcastMainBundle:Playlist:update" }
##    requirements: { _method: post }
##
##playlist_delete:
##    pattern:  /playlist/{id}/delete
##    defaults: { _controller: "PodcastMainBundle:Playlist:delete" }
##    requirements: { _method: post }
##    options:
##      expose: true
##      
##playlist_rename:
##    pattern: /playlist/rename-playlist
##    defaults: {_controller: "PodcastMainBundle:Playlist:rename", _format: json }
##    requirements: {_method: post, _format: json }
##    options:
#      expose: true