categories:
    type:     rest
    resource: Podcast\MainBundle\Controller\CategoryController
    
podcasts:
    type:     rest
    resource: Podcast\MainBundle\Controller\PodcastController
    
organizations:
    type:     rest
    resource: Podcast\MainBundle\Controller\OrganizationController

categories_podcasts:
    type:     rest
    parent:   categories
    resource: Podcast\MainBundle\Controller\CategoryPodcastController