podcasts:
    type:     rest
    resource: Podcast\MainBundle\Controller\PodcastsController
    
categories:
    resource: Podcast\MainBundle\Controller\CategoryController

users:
    type:     rest
    resource: Podcast\MainBundle\Controller\UsersController
    
episodes:
    type:     rest
    resource: Podcast\MainBundle\Controller\EpisodesController