parameters:
    podcast.main.repo.podcast.class: Podcast\MainBundle\Entity\PodcastRepository

services:
    podcast_mainbundle_registrationformtype.form.type:
        class: Podcast\MainBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: podcast_mainbundle_registrationformtype }

    # podcast_mainbundle.update.runner:
    # 	class: Podcast\MainBundle\Update\Runner
    # 	arguments: [@doctrine]