#parameters:
#    podcast_main.example.class: Podcast\MainBundle\Example

#services:
#    podcast_main.example:
#        class: %podcast_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#
parameters:
    security.authentication.success_handler.class: Podcast\MainBundle\Handler\AuthenticationHandler

services:
    security.authentication.success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments:  ['@router', '@security.user.entity_manager']
#    security.authentication.failure_handler:
#        class: %security.authentication.success_handler.class%
#        public: false
#        arguments:  ['@router', '@security.user.entity_manager']