<?php

namespace Podcast\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Podcast\UserBundle\Entity\User;
use Doctrine\ORM\Query;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{
    public function getListenedToIds(User $user)
    {
        $qb = $this->createQueryBuilder('episode');

        $episodeIds = $qb->select('episode.id')
            ->innerJoin('episode.listenedBy', 'user')
            ->where('user.id = :userId')
            ->setParameter('userId', $user->getId())
            ->getQuery()
            ->getResult('numeric_array');

        return $episodeIds;
    }
}
